#!/bin/bash
rm -rf /var/log/nova*
rm -rf /var/log/ntp*
rm -rf /var/log/libvirt*

rm -rf /var/lib/nova*
rm -rf /var/lib/ntp*
rm -rf /var/lib/libvirt*

rm -rf /etc/nova*
rm -rf /etc/ntp*
rm -rf /etc/libvirt*

rm -rf /etc/init/nova*
rm -rf /etc/init/ntp*
rm -rf /etc/init/libvirt*

rm -rf /etc/init.d/nova*
rm -rf /etc/init.d/ntp*
rm -rf /etc/init.d/libvirt*

rm -rf ~/.nova*
