#!/bin/bash
echo "====================================================================="
apt-get -y --purge autoremove bridge-utils
apt-get -y --purge autoremove kvm libvirt-bin
apt-get -y --purge autoremove ntp
apt-get -y --purge autoremove open-iscsi open-iscsi-utils

# remove nova
./same/iptable/clean_iptables
apt-get -y --purge autoremove nova-network nova-compute nova-compute-kvm 
echo "====================================================================="
