#!/bin/bash
#====================================================
# Step 1: Prepare your System
#====================================================
#apt-get -y update
#apt-get -y upgrade

echo 1 > /proc/sys/net/ipv4/ip_forward
apt-get -y install bridge-utils

# kvm
apt-get -y install kvm libvirt-bin

# install ntp and configure
apt-get -y install ntp
file=/etc/ntp.conf
sed -i -e " s/^server ntp.ubuntu.com$/server ${CONTROLLER_IP}/g" $file
service ntp restart

# install iscsi client
apt-get -y install open-iscsi open-iscsi-utils

#====================================================
# Step 2: Install nova-compute
#====================================================
# install nova-compute
apt-get -y install nova-network nova-compute nova-compute-kvm 

# change user group of nova
chown -R nova:nova /etc/nova

file=/etc/nova/api-paste.ini
sed -i -e " s/%SERVICE_TENANT_NAME%/service/g; s/%SERVICE_USER%/nova/g; s/%SERVICE_PASSWORD%/${SERVICE_PASSWORD}/g; " $file
echo "***************************************************"
tail -3 $file
echo "***************************************************"

file=/etc/nova/nova.conf
temp=./same/nova.conf
cat $temp >$file
# replace env to value
sed -i '/${HOST_IP}/{s|${HOST_IP}|'"${HOST_IP}"'|g}' $file
sed -i '/${CONTROLLER_IP}/{s|${CONTROLLER_IP}|'"${CONTROLLER_IP}"'|g}' $file
sed -i '/${ISCSI_IP_PREFIX}/{s|${ISCSI_IP_PREFIX}|'"${ISCSI_IP_PREFIX}"'|g}' $file
sed -i '/${ISCSI_IP_PREFIX}/{s|${ISCSI_IP_PREFIX}|'"${ISCSI_IP_PREFIX}"'|g}' $file
sed -i '/${FIXED_RANGE}/{s|${FIXED_RANGE}|'"${FIXED_RANGE}"'|g}' $file
sed -i '/${FLOATING_RANGE}/{s|${FLOATING_RANGE}|'"${FLOATING_RANGE}"'|g}' $file
sed -i '/${NETWORK_SIZE}/{s|${NETWORK_SIZE}|'"${NETWORK_SIZE}"'|g}' $file
sed -i '/${FLAT_NETWORK_DHCP_START}/{s|${FLAT_NETWORK_DHCP_START}|'"${FLAT_NETWORK_DHCP_START}"'|g}' $file
echo "***************************************************"
cat $file
echo "***************************************************"

# Then, restart all nova services to make the configuration file changes take effect:
file=./same/nova_restart
bash $file

nova-manage service list
nova list
