#!/bin/bash
#====================================================
# Step 1: Prepare your System
#====================================================
#apt-get -y update
#apt-get -y upgrade

echo 1 > /proc/sys/net/ipv4/ip_forward
apt-get -y install bridge-utils

# install ntp and configure
apt-get -y install ntp
file=/etc/ntp.conf
sed -i -e " s/^server ntp.ubuntu.com$/server ${CONTROLLER_IP}/g" $file
